CREATE TABLE IF NOT EXISTS Film (
    film_id int  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    description varchar(200) NOT NULL,
    releaseDate date NOT NULL,
    duration int NOT NULL,
    rating_id int NOT NULL
    );

CREATE TABLE IF NOT EXISTS Likes (
    like_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    film_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    user_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(200) NOT NULL,
    login varchar(50) NOT NULL,
    name varchar(200) NOT NULL,
    birthday date NOT NULL,
    CONSTRAINT uc_User_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS Friendship (
    friendship_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int NOT NULL,
    friend_id int NOT NULL,
    status bool NOT NULL
);

CREATE TABLE IF NOT EXISTS Film_genre (
    Film_genre_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id int NOT NULL,
    genre_id int NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre (
    genre_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    CONSTRAINT uc_Genre_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS RatingMPA (
    rating_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(10) NOT NULL,
    description varchar(200) NOT NULL,
    CONSTRAINT uc_RatingMPA_name UNIQUE (name)
);

ALTER TABLE Film ADD CONSTRAINT IF NOT EXISTS fk_Film_rating_id FOREIGN KEY(rating_id)
    REFERENCES RatingMPA (rating_id) ON DELETE RESTRICT;

ALTER TABLE Likes ADD CONSTRAINT IF NOT EXISTS fk_Like_user_id FOREIGN KEY(user_id)
    REFERENCES Users (user_id);

ALTER TABLE Likes ADD CONSTRAINT IF NOT EXISTS fk_Like_film_id FOREIGN KEY(film_id)
    REFERENCES Film (film_id) ON DELETE CASCADE;

ALTER TABLE Friendship ADD CONSTRAINT IF NOT EXISTS fk_Friendship_user_id FOREIGN KEY(user_id)
    REFERENCES Users (user_id);

ALTER TABLE Friendship ADD CONSTRAINT IF NOT EXISTS fk_Friendship_friend_id FOREIGN KEY(friend_id)
    REFERENCES Users (user_id);

ALTER TABLE Film_genre ADD CONSTRAINT IF NOT EXISTS fk_Film_genre_film_id FOREIGN KEY(film_id)
    REFERENCES Film (film_id) ON DELETE CASCADE;

ALTER TABLE Film_genre ADD CONSTRAINT IF NOT EXISTS fk_Film_genre_genre_id FOREIGN KEY(genre_id)
    REFERENCES Genre (genre_id) ON DELETE RESTRICT;

ALTER TABLE Film_genre ADD CONSTRAINT IF NOT EXISTS UC_Film_genre_genre_id_film_id UNIQUE (genre_id, film_id);